---

# - name: ensure apache2 is stopped
#   systemd:
#     name: apache2
#     state: stopped

- name: ensure nginx is installed.
  apt:
    name: nginx
    state: present
    update_cache: "yes"

- name: ensure nginx configuration file is present
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-available/matomo
  notify: reload nginx

- name: ensure symbolink is present
  file:
    src: /etc/nginx/sites-available/matomo
    dest: /etc/nginx/sites-enabled/matomo
    state: link
  notify: reload nginx

- name: disable the default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx
